{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "atlas.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atlas.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "atlas.selectorLabels" . | nindent 6 }}
{{- end }}
